### ISSUE TITLE
Subliminal continues to give ERROR

### ISSUE THREAD

**Issue by Diego4488** [Diego4488/redesigned-tribble#1]
Essentially, that's what happens every time I wish to input a file directory. I'm a complet noob and I am running Linux Mint, latest distro, with XFCE desktop. 

The real issue is this QUOTE

Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.7.5', 'console_scripts', 'subliminal')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/subliminal/__init__.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/subliminal/cache.py", line 5, in <module>
ImportError: No module named compat

ANY CLUES?? I'm going nuts. Thanks a ton.

**Comment by Diego4488** [comment]
Is there anybody outhere??? 
Hi everyone, i'm pretty new at dealing with command line and my knowledge is ZERO.... I' ve been struggling for weeks with Subliminal, which is a Python command line to download subtiltes "en masse"... Like bulk download or batch download. I'm at the starting point and nevertheless I can manage to make it work...

Can somebody please give me a hint as to how the heck can I make this work??? I have an NTFS partition, and of course, it wouldn't work either, but know i'm trying to use my Home directory, which es EXT4 and still.....nothing happens... At first, I tryied via Docker, but didn't work. Now, I'm trying with the following command... and didn't work either!!!


subliminal download -l--spa--[home/diego44/Descargas/]


subliminal download -l--spa--[home/diego44/Descargas/]
Traceback (most recent call last):
File "/usr/bin/subliminal", line 9, in <module>
load_entry_point('subliminal==0.7.4', 'console_scripts', 'subliminal')()
File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in subliminal
args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in <setcomp>
args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
File "/usr/lib/python3/dist-packages/babelfish/language.py", line 126, in fromietf
language = cls(language_subtag)
File "/usr/lib/python3/dist-packages/babelfish/language.py", line 82, in __init__
raise ValueError('%r is not a valid language' % language)
ValueError: '' is not a valid language



subliminal download -l spa --EN--[home/diego44/Descargas/]
usage: subliminal -l LANGUAGE [LANGUAGE ...] [-s] [-c CACHE_FILE]
[-p PROVIDER [PROVIDER ...]] [-m MIN_SCORE] [-a AGE] [-h]
[-f] [--addic7ed-username USERNAME]
[--addic7ed-password PASSWORD] [-q | -v] [--color] [--debug]
[--version] [--help]
PATH [PATH ...]
subliminal: error: unrecognized arguments: --EN--[home/diego44/Descargas/]



subliminal download -l spa --EN--[home/diego44/Descargas/]
usage: subliminal -l LANGUAGE [LANGUAGE ...] [-s] [-c CACHE_FILE]
[-p PROVIDER [PROVIDER ...]] [-m MIN_SCORE] [-a AGE] [-h]
[-f] [--addic7ed-username USERNAME]
[--addic7ed-password PASSWORD] [-q | -v] [--color] [--debug]
[--version] [--help]
PATH [PATH ...]
subliminal: error: unrecognized arguments: --EN--[home/diego44/Descargas/]




subliminal download -l--EN--[home/diego44/Descargas/The Walking Dead S01-06 720p BluRay x264 Pahe.in]
usage: subliminal -l LANGUAGE [LANGUAGE ...] [-s] [-c CACHE_FILE]
[-p PROVIDER [PROVIDER ...]] [-m MIN_SCORE] [-a AGE] [-h]
[-f] [--addic7ed-username USERNAME]
[--addic7ed-password PASSWORD] [-q | -v] [--color] [--debug]
[--version] [--help]
PATH [PATH ...]
subliminal: error: unrecognized arguments: Walking Dead S01-06 720p BluRay x264 Pahe.in]



subliminal download -l --EN -/home/diego44/Descargas/The Walking Dead S01-06 720p BluRay x264 Pahe.in/
usage: subliminal -l LANGUAGE [LANGUAGE ...] [-s] [-c CACHE_FILE]
[-p PROVIDER [PROVIDER ...]] [-m MIN_SCORE] [-a AGE] [-h]
[-f] [--addic7ed-username USERNAME]
[--addic7ed-password PASSWORD] [-q | -v] [--color] [--debug]
[--version] [--help]
PATH [PATH ...]
subliminal: error: argument -l/--languages: expected at least one argument


AND FINALLY, THE DOCKER ATTEMPT...

docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /tvshows:/tvshows -it diaoulael/subliminal download -l en /home/diego44/Descargas/The Walking Dead S01-06 720p BluRay x264 Pahe.in
Collecting videos [####--------------------------------] 12% /home/diego44/Descargas/The
Traceback (most recent call last):
File "/usr/local/bin/subliminal", line 9, in <module>
load_entry_point('subliminal', 'console_scripts', 'subliminal')()
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
return f(get_current_context().obj, *args, **kwargs)
File "/usr/src/app/subliminal/cli.py", line 326, in download
video.subtitle_languages |= set(search_external_subtitles(video.name, directory=directory).values())
File "/usr/src/app/subliminal/core.py", line 339, in search_external_subtitles
for p in os.listdir(directory or dirpath):
FileNotFoundError: [Errno 2] No such file or directory: '/home/diego44/Descargas


Can somebody please, please...please....aid me in my sorrow??? I'm running Linux Mint 18 Sarah, XFCE desktop.

In advance, thanks a ton. My best regards to you all.
